apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: john-certificate
  namespace: sock-shop
spec:
  secretName: johnny-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: www.gbochidev.tech
  dnsNames:
  - www.gbochidev.tech